### ISSUE TITLE
What is best practice for using BPOE?

### ISSUE THREAD

**Issue by bartonhammond** [sensiolabs/BehatPageObjectExtension#108]
It seems to me, when using BPOE, that each Feature needs to have it's own pair or Context & POM.  That keeps things organized, at least in my mind.

It also means there is duplicated code.  I currently have 2 Features and both of my Contexts have "I am on the ?? page" and "I should see the ?? link".  I want to make sure when confirming certain links are visible, that I'm testing with the correct POM.

That's all fine when testing Features/Scenarios.  But I have to also run my tests w/ CrossBrowserTesting so we can verify all the pages perform correctly and look right.  Rather then have our UI guy look through all the screen shots from multiple Features, I'd like to build one Feature that contains `happy path` solution.  My problem is, if I separate all the Features/Contexts, I don't think I'll be able to make this `happy path` solution as I won't the appropriate Context.

Do you have a recommendation on how to address this?  Also, do you have any example projects that are using BPOE that you would recommend?  Yes - I've searched for them.  I've not found one that is anything more then a simple example.

Thanks.

**Comment by DonCallisto** [comment]
Usually I split my context for "Subject --> Action", something like "User --> SignupContext, LoginContext, ResetPasswordContext" and so on.
It could be the case where contexts has same steps: I don't mind as I build my suites as follows

```
default:
  suites:
    ui_alunno_import:
      paths:
        - '%paths.base%/Features/Alunno'
      contexts:
        - NuvolaBehat\Context\Ui\Alunno\ImportContext
        - NuvolaBehat\Context\Ui\Ata\ScegliAreaDiLavoroContext
        - NuvolaBehat\Context\Ui\Hook\UiHookContext
        - NuvolaBehat\Context\Ui\Utente\ImpersonaContext
        - NuvolaBehat\Context\Ui\Utente\LoginContext
      filters:
        tags: "@alunno_import && @ui" 
```

This way I use only `Context` that I really need.

Don't know if this can help you.
Moreover I can't see how this problem could be related to this extension.
