### ISSUE TITLE
Fatal error: Call to a member function createPage() on null (Behat\Testwork\Call\Exception\FatalThrowableError)

### ISSUE THREAD

**Issue by bartonhammond** [sensiolabs/BehatPageObjectExtension#109]
My Context:
```
    /**
     * @When I go to the :arg1 page
     */
    public function iGoToThePage($arg1) {
        $this->currentPage = $this->getPage($arg1);
        assertTrue($this->currentPage->verifyPage());
    }
```

The Feature
```
   When I go to the "Home Page" page  
```
`behat.yml`
```
default:
  suites:
    home:
      paths:
         - "%paths.base%/features/home.feature"
      page:
        - ["%paths.base%/features/bootstrap/page-objects/page"]
      contexts:
        - HomeContext
```

My HomePage in `features/bootstrap/page-objects/page/HomePage.php`
```
<?php
namespace Page;
use SensioLabs\Behat\PageObjectExtension\PageObject\Page;
class HomePage extends Page {
  protected $path = '';
  protected $elements = [
....
```

When I run ` vendor/bin/behat --config behat.yml --colors --tags wip`
```
~/projects/uwce/www (develop)$ vendor/bin/behat --config behat.yml --colors --tags wip
Feature: HomePage
  In order to navigate all the campuses
  As a visitor
  I want to access any campus
  
  Background

  @javascript @wip
  Scenario: I can login to my campus                     # features/home.feature:48
    Given I am a visitor                                 # HomeContext::iAmAVisitor()
    When I go to the "Home Page" page                    # HomeContext::iGoToThePage()
      Fatal error: Call to a member function createPage() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
    And I click the "UW-Fond du Lac (Staging)" link      # HomeContext::iClickTheLink()
 ```
