### ISSUE TITLE
Expected to be on "xxx" but found "" instead 

### ISSUE THREAD

**Issue by bartonhammond** [sensiolabs/BehatPageObjectExtension#111]
I'm using MinkExtension and running locally is fine.  But when I try to run w/ CrossBrowserTesting I fail.  I'm working on extending MinkExtension w/ a CBT Factory patterned after BrowserStack Factory.

Anyway, here is my `behat-cbt.yml`
```
default:
  suites:
    default:
      paths: ["%paths.base%/features/temp/home.feature"]
      local_screenshots: false      
      contexts: [ThinkWellContext]

  extensions:
    Behat\MinkExtension:
      default_session: my_session
      base_url: https://twlw.wpengine.com
      browser_name: 'chrome'      
      sessions:
        my_session:
          cross_browser_testing:
            server: "crossbrowsertesting.com"
            user: "b@wist.com"
            key: "ud"
            capabilities: 
              name: "Name"
              build: "1.0.0"
              record_video: true
              record_network: true
              max_duration: "14400"
              browserName: 'Chrome'
              version: '62x64'
              platform: 'Mac OSX 10.12'
              screenResolution: '1366x768'
              
    SensioLabs\Behat\PageObjectExtension:
      namespaces:
        page: [Page]
        element: [Page]
```
Heres the output:
```
~/projects/thinkwell-livewell/wp-content/themes/jumpoff (master)$ vendor/bin/behat --config behat-cbt.yml 
Feature: Home
  In order to navigate the site
  As a visitor
  I want to test navigation

  Background:                           # features/temp/home.feature:6
    Given I reset "all" data            # ThinkwellContext::iResetData()
      │ Reset Post Data
      │ Reset User Program Data
      │ Reset User Data
      │ 
    Given I am a visitor                # ThinkwellContext::iAmAVisitor()
    When I go to the "Home" page        # ThinkwellContext::iGoToThePage()
      Expected to be on "https://twlw.wpengine.com/" but found "" instead (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException)
    And I take a screenshot "home page" # ThinkwellContext::iTakeAScreenshot()

  @javascript
  Scenario: I can see multiple links            # features/temp/home.feature:13
    Then I should see "Programmes" link         # ThinkwellContext::iShouldSeeLink()
    And I should see "How It Works" link        # ThinkwellContext::iShouldSeeLink()
    And I should see "Self-Help/Resources" link # ThinkwellContext::iShouldSeeLink()
    And I should see "Try It Free" link         # ThinkwellContext::iShouldSeeLink()
    And I take a screenshot "Home page"         # ThinkwellContext::iTakeAScreenshot()

--- Failed scenarios:

    features/temp/home.feature:13

1 scenario (1 failed)
9 steps (2 passed, 1 failed, 6 skipped)
```

I'm not seeing any activity w/in CBT.  I'm kind of lost to how to debug this.  My experience has been when I see a similar message to this that the browser was never started.  I don't see any browser starting.
