### ISSUE TITLE
Clicking link, when emulating device, does not work

### ISSUE THREAD

**Issue by bartonhammond** [sensiolabs/BehatPageObjectExtension#113]
When I run my script against Chrome browser, it works fine.  
When I change the `capabilities` to emulate Galaxy S5, the click on link does not work
```
        capabilities:
          extra_capabilities:
            chromeOptions:
              mobileEmulation:
                deviceName: Galaxy S5
```
I use PsySh and can use these statements (which the code also does)
```
>>>  $link = $parent->getElement($linkname);
=> SensioLabs\Behat\PageObjectExtension\PageObject\InlineElement {#8076}
>>> $link->click()
=> null
```
Nothing happens & I see no error in the developers console.  

The xpath is `//a[contains(@href,'register/one-month')]`

When I use the following w/in the developers console, the click works:
```
foo = $x("//a[contains(@href,'register/one-month')]")[0]
foo.click()
```
Any suggestion on how to debug this?

Thanks!
