### ISSUE TITLE
Using PageObjectExtension in multiple Symfony2 bundles

### ISSUE THREAD

**Issue by qpleple** [sensiolabs/BehatPageObjectExtension#5]
Hi,
Is there a way to use PageObjectExtension when features are organized in Symfony2 bundles? The issue I'm running into is that I will end up having some classes Page in each of my bundles, next to the features, but I can only specify one namespace in `namespaces.page`.

``` yaml
default:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: 'http://short'
            goutte: ~
            selenium2: ~
            default_session: 'symfony2'
        SensioLabs\Behat\PageObjectExtension\Extension:
            namespaces:
                page: Short\SiteBundle\Features\Page
        Behat\Symfony2Extension\Extension:
            mink_driver: true
```

A workaround, maybe, is to define one profile per bundle, but we can't run all tests at once:

``` yml
site:
    # ...
    extensions:
        Behat\Symfony2Extension\Extension:
            bundle: ShortSiteBundle
        SensioLabs\Behat\PageObjectExtension\Extension:
            namespaces:
                page: Short\SiteBundle\Features\Page
admin:
    # ...
    extensions:
        Behat\Symfony2Extension\Extension:
            bundle: ShortAdminBundle
        SensioLabs\Behat\PageObjectExtension\Extension:
            namespaces:
                page: Short\AdminBundle\Features\Page
```
