### ISSUE TITLE
Access to entity manager inside page object in V3

### ISSUE THREAD

**Issue by tristanbes** [sensiolabs/BehatPageObjectExtension#52]
Hi,

Using behat V3, i'm trying to do what I used to do in V2 with page object:  convert a name into an ID in order to access the url.

Simple example: 

``` php
class AdminListFaq extends Page
{
    /**
     * @var string $path
     */
    protected $path = '/{id}/faq/list';

    /**
     * {@inheritdoc}
     */
    protected function getPath()
    {
       $site = $this->entityManager->getRepository('Model:Site')->findOneByHost($this->parameter);

        return strtr($this->path, ['{id}' => $site->getId()]);
    }
```

And in Page 

``` php
/**
 * Page
 */
class Page extends BasePage
{
    /**
     * The symfony kernel
     *
     * @var KernelInterface $kernel
     */
    protected $kernel;

    /**
     * The symfony container
     * @var Symfony\Component\DependencyInjection\ContainerInterface container
     */
    protected $container;

    /**
     * The doctrine entity manager
     * @var Doctrine\ORM\EntityManager
     */
    protected $entityManager;

    /**
     * The parameter
     *
     * @var mixed parameter
     */
    protected $parameter;

    /**
     * Set KernelInterface
     *
     * @param KernelInterface $kernel
     */
    public function setKernel(KernelInterface $kernel)
    {
        $this->kernel        = $kernel;
        $this->container     = $kernel->getContainer();
        $this->entityManager = $this->container->get('doctrine.orm.entity_manager');
    }

.....
```

It was working in V2, but not in V3 (the entityManager is `null`). Am I missing something please ?

PS: My Behat config is : 

``` yaml
default:
    autoload: %paths.base%/features/Context
    extensions:
        Behat\MinkExtension:
            base_url:   http://example.dev/admin_behat.php
            files_path: apps/features/files
            default_session:    goutte
            javascript_session: selenium2
            goutte:    ~
            selenium2: ~
        Behat\Symfony2Extension:
            kernel:
                env:   behat
                debug: true
                path: admin/AdminKernel.php
                class: AdminKernel
                bootstrap: apps/autoload.php
        SensioLabs\Behat\PageObjectExtension:
            namespaces:
                page: Context\Page
                element: Context\Page\Element
        VIPSoft\DoctrineDataFixturesExtension\Extension:
            lifetime:    feature
            autoload:    false
            directories:
                - apps/features/Context/Fixtures
            fixtures:    ~
            migrations: ~
        Sanpi\Behatch\Extension: ~
    suites:
        default:
            contexts:
                - Context\FeatureContext
                - Context\UserContext
                - Context\PageContext
                - behatch:browser
                - behatch:debug
```
