### ISSUE TITLE
Extension not found

### ISSUE THREAD

**Issue by khusseini** [sensiolabs/BehatPageObjectExtension#53]
Hi there,

I have followed the docs to install the extension, however I cannot get it to work. I keep getting 

```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
`SensioLabs\Behat\PageObjectExtension` extension file or class could not be located.
```

Here my config:

```
default:
        extensions:
                SensioLabs\Behat\PageObjectExtension: ~
                Behat\MinkExtension:
                        base_url:  'http://localhost'
                        sessions:
                                default:
                                        selenium2: ~
```

Directory structure is standard composer. I did a behat --init also in my project folder.
