### ISSUE TITLE
To create pages you need to pass a factory with setPageObjectFactory() (RuntimeException)

### ISSUE THREAD

**Issue by khusseini** [sensiolabs/BehatPageObjectExtension#54]
My behat.yml

```
default:
        autoload:
                '': %paths.base%/src
        suites:
                default:
                        contexts: [Context\SearchContext]
                        extensions:
                                SensioLabs\Behat\PageObjectExtension: ~
                                Behat\MinkExtension:
                                        base_url:  'http://en.wikipedia.org'
                                        sessions:
                                                default:
                                                        selenium2: ~
```

My Context:

```
<?php

namespace Context;

use Behat\Behat\Tester\Exception\PendingException;
use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\MinkExtension\Context\MinkContext;
use SensioLabs\Behat\PageObjectExtension\Context\PageObjectAware;

/**
 * Defines application features from the specific context.
 */
class SearchContext extends ContextBase {

    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct() {

    }

    /**
     * @Then I should see the login flyout open
     */
    public function iShouldSeeTheLoginFlyoutOpen() {
        throw new PendingException();
    }
}
```

Context Base:

```
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace Context;

use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Behat\Tester\Exception\PendingException;
use SensioLabs\Behat\PageObjectExtension\Context\PageObjectContext;


/**
 * Description of ContextBase
 *
 * @author KEH
 */
abstract class ContextBase extends PageObjectContext implements SnippetAcceptingContext {

    /**
     *
     * @var SensioLabs\Behat\PageObjectExtension\PageObject\Page
     */
    protected $page = null;

    /**
     * @Given I am on the homepage
     */
    public function iAmOnTheHomepage() {
        $this->iVisitedThePage('Homepage');
    }

    /**
     * @Given /^(?:|I )visited (?:|the )(?P<pageName>.*?)$/
     */
    public function iVisitedThePage($pageName) {
        $this->page = $pageName;
        $this->getPage($pageName)->open();
    }

    /**
     * @When I mouse over :elementSelector
     */
    public function iMouseOver($elementSelector) {
        throw new PendingException();
    }

}
```

And my folder structure:

```
|->bin
|->features
|  |-> login.feature
|->src
|  |->Context 
|  |  |->SearchContext.php (namespace Context)
|  |  |->ContextBase.php (namespace Context)
|  |
|  |->Page
|  |   |->Homepage.php (namespace Page)
|->vendor
|->behat.yml
```

Can you help me get the factory right?
