### ISSUE TITLE
Fatal error: Call to a member function open() on null

### ISSUE THREAD

**Issue by nietzscheson** [sensiolabs/BehatPageObjectExtension#98]
My project works on Vagrant with Docker Engine. I have the follow configurations in behat:

```yml
###behat.yml
default:

    extensions:
        Behat\MinkExtension:
            base_url: "http://192.168.33.10/app_test.php/"
#            default_session: chrome
            javascript_session: chrome
            sessions:
                chrome:
                    selenium2:
                        wd_host: "http://192.168.33.10:4444/wd/hub/"
                        browser: chrome
                        capabilities:
                            browserName: chrome
                            browser: chrome
                            version: ""
                            chrome:
                                switches:
                                    - "start-fullscreen"
                                    - "start-maximized"
                                    - "no-sandbox"

        SensioLabs\Behat\PageObjectExtension: ~

### sign_in.feature
@security
Feature: Sign in into Application

    @ui
    Scenario: Search
        Given I am on the login
        When I fill the username with "user@usuario.com"
        And I fill the password with "password"
        When I want a login
        Then I should see "Credenciales no válidas."
 ```
```php
class SecurityContext implements Context
{

private $loginPage;

public function __construct(LoginPage $loginPage)
{
  $this->loginPage = $loginPage;
}

/**
 * @Given I am on the login
 */
public function iAmOnTheLogin()
{
   $this->loginPage->open();
}
```
When I run behat it fails and throws me the error: Fatal error: Call to a member function open() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
